trying store style errors

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -31,7 +31,10 @@ jobs:
                   line=$(echo $ERROR | cut -d ':' -f 2)
                   gravity=$(echo $ERROR | awk -F ':' '{print $3}')
                   error=$(echo $ERROR | awk -F ':' '{print $4}')
-                  url=$(echo "https://www.youtube.com/watch?v=dQw4w9WgXcQ")
-                  echo "::error file=$filename,line=$line,title=$gravity coding style error,url=https://myproject.com/errors/123::$error"
+                  echo "::error file=$filename,line=$line,title=$gravity coding style error::$error"
                 done < coding-style-reports.log
+                if (cat coding-style-reports.log | wc -l) -gt 0
+                then
+                  exit 1
+                fi
                 
